apiVersion: v1
kind: Service
metadata:
  name: k8s-app-backend-service
  labels:
    app: k8s-app-backend
spec:
  type: LoadBalancer
  selector: 
    app: k8s-app-backend
    ports:
      - protocol: TCP
        name: http
        port: 8080
        targetPort: 8080
        nodePort: 30001