apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    name: mysql-service
    app: k8s-app
spec:
  ports:
  - port:  3306
    targetPort: 3306
  selector:
    name: mysql-pod
    app: k8s-app
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: db-pvc
  labels: k8s-app
spec: 
  accessMode: 
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deploy
  labels:
    name: mysql-deploy
    app: k8s-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-app
  strategy: Recreate
  template:
    metadata:
      name: mysql
      labels:
        name: mysql-pod
        app: k8s-app
    spec:
      containers:
      - name: mysql
        image: mysql
        ports:
          - containerPort: 3306
        env:
          - name: MYSQL_DATABASE
            valueFrom:
              configMapKeyRef:
                name: db-config-map
                key: database-name
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-secret-password
                key: db-root-password
          - name: MYSQL_USER
            valueFrom:
              configMapKeyRef:
                name: db-config-map
                key: db-user-username
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-secret-password
                key: db-user-password
        livenessProbe:
          tcpSocket: 
            port: 3306
      ports:
        - containerPort: 3306
          name: db
      volumeMounts:
        - name: db-persistent-storage
          persistentVolumeClaim:
            claimName: db-pvc
