apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    name: mysql-service
    app: k8s-app
spec:
  ports:
  - port:  3306
    targetPort: 3306
  selector:
    name: mysql-pod
    app: k8s-app